AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        # AttributeDefinitions items must be in our table
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        # KeySchema tells dynamo db what to do with the schema
        KeySchema:
          - AttributeName: Id
            KeyType: HASH