# this resource to enable function url of the lambda function
DownloadPdfUrl:
  Type: AWS::Lambda::Url
  Properties:
    AuthType: NONE
    # to stream response of function
    InvokeMode: RESPONSE_STREAM
    # function logical name get it from serverless package
    TargetFunctionArn: !Ref OrderReceiptLambdaFunction

# permission so lambda function url is publicly avaiable
PermissionForURLInvoke:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref OrderReceiptLambdaFunction
    # none so public can access it
    FunctionUrlAuthType: "NONE"
    Action: lambda:InvokeFunctionUrl
    Principal: "*"
