# cloudwatch can put the data in firehouse deleivery stream
# allow cloudwatch to call aws firehouse
# https://gist.github.com/shortjared/4c1e3fe52bdfa47522cfe5b41e5d6f22

CloudWatchIAM:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - logs.amazonaws.com #cloudwatch principal that will assume the rule
          Action:
            - "sts:AssumeRole"
    Policies:
      - PolicyName: root
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - firehose:PutRecordBatch
                - firehose:PutRecord
              Resource: !GetAtt DeliveryStream.Arn
