service: apollo-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

custom:
  webpack:
    webpackConfig: "webpack.config.js"
  httpApi:
    cors: true

functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
  - serverless-webpack

  # // serverless invoke local -f graphql -p query.json
