service: apollo-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

package:
  patterns:
    - "!@aws-sdk/*"

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
    includeModules:
      forceExclude:
        - "@aws-sdk/*"
  httpApi:
    cors: true

functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
  - serverless-webpack

  # // serverless invoke local -f graphql -p query.json
