SocketsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: ConnectionId
        AttributeType: S
    KeySchema:
      - AttributeName: ConnectionId
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TableName: WebsocketConnections-${self:provider.stage}
