service: books-service

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  deploymentBucket:
    name: ${env:BUCKET_NAME}

plugins:
  - serverless-plugin-typescript
  - serverless-appsync-plugin

# functions:
#   getBookById:
#     handler: src/getBookById.handler

# you can add CloudFormation resource templates here
resources:
  Resources:
    BooksTable: ${file(./resources/DynamoTable.yml):BooksTable}
    OrdersTable: ${file(./resources/DynamoTable.yml):OrdersTable}
    CognitoUserPool: ${file(./resources/Cognito.yml):CognitoUserPool}
    CognitoUserPoolClient: ${file(./resources/Cognito.yml):CognitoUserPoolClient}
    CongitoAdminGroup: ${file(./resources/Cognito.yml):CongitoAdminGroup}
    CongitoCustomGroup: ${file(./resources/Cognito.yml):CongitoCustomGroup}
    CongitoAdminIAMRole: ${file(./resources/Cognito.yml):CongitoAdminIAMRole}
    CongitoCustomersIAMRole: ${file(./resources/Cognito.yml):CongitoCustomersIAMRole}
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

# custom:
#   appSync:
#     name: books
#     authenticationType: AMAZON_COGNITO_USER_POOLS
#     additionalAuthenticationProviders:
#       - authenticationType: AWS_IAM
#     userPoolConfig:
#       awsRegion: us-east-1
#       defaultAction: ALLOW
#       userPoolId: !Ref cognitoUserPool
#     mappingTemplatesLocation: mapping-templates
#     mappingTemplates:
#       - type: Query
#         field: getBookById
#         dataSource: booksTable
#       - type: Query
#         field: listBooks
#         dataSource: booksTable
#       - type: Mutation
#         field: createBook
#         dataSource: booksTable
#     dataSources:
#       - type: AMAZON_DYNAMODB
#         name: booksTable
#         config:
#           tableName: !Ref BooksTable

appSync:
  name: books-${self:provider.stage}
  authentication:
    type: "AMAZON_COGNITO_USER_POOLS"
    config:
      awsRegion: us-east-2
      defaultAction: ALLOW
      userPoolId: !Ref CognitoUserPool
  # schema:
  #   - "schema.graphql"
  pipelineFunctions:
    getBookById:
      # dataSource: booksTable
      dataSource:
        type: "AWS_LAMBDA"
        config:
          function:
            timeout: 30
            handler: "src/getBookById.handler"
    listBooks:
      dataSource:
        type: "AWS_LAMBDA"
        config:
          function:
            timeout: 30
            handler: "src/listBooks.handler"
    createBook:
      dataSource:
        type: "AWS_LAMBDA"
        config:
          function:
            timeout: 30
            handler: "src/createBook.handler"

  resolvers:
    Query.getBookById:
      dataSource: booksTable
      functions:
        - getBookById
    Query.listBooks:
      dataSource: booksTable
      functions:
        - listBooks
    createBook:
      type: Mutation
      field: createBook
      functions:
        - createBook
    # getBook:
    #   type: Query
    #   field: getBookById
    #   functions:
    #     - getBookById
  dataSources:
    booksTable:
      type: AMAZON_DYNAMODB
      description: "dynamo db table"
      config:
        tableName: !Ref BooksTable
# {type}.{field}.request.vtl , {type}.{field}.response.vtl
# https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html
# request helps appsync make a request to dynamo db
# https://github.com/sid88in/serverless-appsync-plugin
# https://github.com/sid88in/serverless-appsync-plugin
